// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20251028203203_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("DAL.Models.BoardCellEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Column")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameStateId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Row")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameStateId");

                    b.ToTable("BoardCells");
                });

            modelBuilder.Entity("DAL.Models.GameStateEntity", b =>
                {
                    b.Property<string>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<int>("BoardHeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoardShape")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BoardWidth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentPlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGameOver")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Player1AiDifficulty")
                        .HasColumnType("TEXT");

                    b.Property<string>("Player1Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Player1IsAi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Player1Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Player2AiDifficulty")
                        .HasColumnType("TEXT");

                    b.Property<string>("Player2Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Player2IsAi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Player2Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WinnerName")
                        .HasColumnType("TEXT");

                    b.Property<int>("WinningConnection")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId");

                    b.ToTable("GameStates");
                });

            modelBuilder.Entity("DAL.Models.BoardCellEntity", b =>
                {
                    b.HasOne("DAL.Models.GameStateEntity", "GameState")
                        .WithMany("BoardCells")
                        .HasForeignKey("GameStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameState");
                });

            modelBuilder.Entity("DAL.Models.GameStateEntity", b =>
                {
                    b.Navigation("BoardCells");
                });
#pragma warning restore 612, 618
        }
    }
}
